---
deployment:
  tasks:
    # Define the deployment path
    - export DEPLOYPATH=/home/example/public_html/

    # Install Composer dependencies
    - /usr/local/bin/composer install --no-dev --optimize-autoloader

    # Clear the cache
    - php bin/console cache:clear --env=prod --no-debug

    # Install assets
    - php bin/console assets:install $DEPLOYPATH

    # Copy all necessary files to the deployment path
    - /bin/cp -R * $DEPLOYPATH

    # Set appropriate permissions
    - /bin/chmod -R 755 $DEPLOYPATH
